version: "3.8"

services:
  web:
    build: .
    container_name: cliente1_web
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cliente1.rule=PathPrefix(`/`)"
      - "traefik.http.routers.cliente1.entrypoints=web"
      - "traefik.http.routers.cliente1.priority=1"
      - "traefik.http.services.cliente1.loadbalancer.server.port=80"
    networks:
      - web

networks:
  web:
    external: true
